### ISSUE TITLE
最新版本的loader有问题？报错！

### ISSUE THREAD

**Issue by 1021683053** [aui/art-template-loader#1]
![image](https://cloud.githubusercontent.com/assets/7711802/25312701/a3e5c0ac-2852-11e7-913b-4832e397e38f.png)
![image](https://cloud.githubusercontent.com/assets/7711802/25312704/af21176e-2852-11e7-8c57-c1802919b271.png)

以下这两个版本没问题，没有尝试是loader的问题还是 模板引擎的问题！

"art-template": "4.2.0",
"art-template-loader": "1.0.0"

**Comment by aui** [comment]
最近在频繁的更新，这个问题可能是 art-template-loader 版本太低了。安全起见，所有的版本都升级到最新吧

**Comment by 1021683053** [comment]
![image](https://cloud.githubusercontent.com/assets/7711802/25314757/821828d2-287c-11e7-811b-40611fe321db.png)
明天我看一下，什么原因。

**Comment by aui** [comment]
@1021683053 找到原因了，没有配置 options 导致的。我已经发布新的修复版本 v1.22 解决了此问题

**Comment by 1021683053** [comment]
@aui 刚想看呢，刚看到更新了！多谢了哈！
