### ISSUE TITLE
关于模板嵌套的问题

### ISSUE THREAD

**Issue by tuhongwei** [aui/art-template-loader#22]
artTemplate貌似不支持嵌套
我在模板里面有一个表达式是这样的：
<%= from ? "from=<%= from %>&" : "" %>，一个三目运算符，报错了，应该不是我写错的原因，如果不支持嵌套，作者可以考虑一下支持嵌套

**Comment by aui** [comment]
为什么不用 js 直接拼接字符串，而要设计一个奇怪的语法来实现你的逻辑呢？

**Comment by tuhongwei** [comment]
是这样的，from是一个变量，是从后台通过请求得来的，我把请求的所有数据都传到模板文件里面，其中在模板文件里面要判断from存不存在，存在的话就执行某一操作，不存在的话执行另一操作，这样我通过if去判断是能够完成需求的，然后我想简化一下代码，想着用三目运算符能否实现，结果嵌套的时候就报错了，貌似它和"<%= "匹配的时候匹配的是最近的一个 "%>"

**Comment by aui** [comment]
三元表达式也可以拼接字符串
