### ISSUE TITLE
include问题

### ISSUE THREAD

**Issue by xiabingwu** [aui/art-template-loader#25]
为什么使用
{{include ‘./preview/’+subType}} 会报错
显示的指出文件扩展名就不报错了
{{include ‘./preview/’+subType+‘.html‘}} 工作正常

**Comment by aui** [comment]
修改默认的后缀名可以看下 art-template 的配置文档

**Comment by xiabingwu** [comment]
![image](https://user-images.githubusercontent.com/5018468/35387994-f3b320fe-020c-11e8-9150-7eb1511a65e3.png)
是有配置的
{{include './subType'}} #编译通过
{{include '../../preview/'+subType'}} # 编译不通过
{{include '../../preview/'+subType+'.html'}} #编译通过

**Comment by aui** [comment]
第二个多了一个逗号

**Comment by xiabingwu** [comment]
那个是笔误，实际代码没有多引号，是{{include '../../preview/'+subType}} 没有编译通过。报错的信息是
![image](https://user-images.githubusercontent.com/5018468/35439998-6daf0974-02d8-11e8-9558-e751a44237c2.png)

等项目忙完了，我把demo准备好放进来
