### ISSUE TITLE
和vue冲突{{ }}

### ISSUE THREAD

**Issue by yiqianglin** [aui/art-template-loader#28]
webpack+vue+artTemplate作为模板引擎，结果vue的{{}}被art-template-loader解析了，怎么能让art不解析{{}}，或者只解析原始语法？
![image](https://user-images.githubusercontent.com/15794229/36072670-7c162762-0f5e-11e8-8b61-03b3a5316d48.png)
红框可以正常解析，但是箭头处是vue的data，但是被art-template-loader解析了。就出问题了

**Comment by yiqianglin** [comment]
目前用了
![image](https://user-images.githubusercontent.com/15794229/36072796-3ba53198-0f61-11e8-9cad-0180573316a1.png)
，但是很不方便，也会存在安全问题。

**Comment by yiqianglin** [comment]
顶一下，没有解决方案吗？

**Comment by yiqianglin** [comment]
顶一下，有解决方案吗？

**Comment by aui** [comment]
<https://aui.github.io/art-template/zh-cn/docs/syntax.html>

**Comment by yiqianglin** [comment]
所以是因为语法问题，并不能跟vue，或者jsx进行渲染？

**Comment by aui** [comment]
上面那个文档地址可能有些问题，在这里：<https://aui.github.io/art-template/zh-cn/docs/rules.html>
