### ISSUE TITLE
是否支持 img src 交给 webpack 处理？

### ISSUE THREAD

**Issue by zcoding** [aui/art-template-loader#3]
有没有可能像 `html-loader` 一样，把 `<img>` 的 `src` 属性的值交给 webpack 的其它 loader 来 require ，这样就可以使用 `file-loader` 等。

这里说的 `<img>` 主要是指那些非变量的情况。如果通过变量传给 art-template 当然也是可以，但这样就麻烦了点。

主要是为了方便图片重命名、加 CDN 前缀等情况。

**Comment by aui** [comment]
好建议。考虑支持

**Comment by aui** [comment]
已经支持。同时将 art-template 与 art-template-loader 更新到最新版本即可
