### ISSUE TITLE
每次修改都要执行 npm run ,有没有实时编译的？

### ISSUE THREAD

**Issue by web-chenke** [aui/art-template-loader#40]
每次修改都要执行 npm run ,有没有实时编译的？

**Comment by aui** [comment]
你可以去了解下 webpack 的 watch

**Comment by web-chenke** [comment]
只有改模板的时候   执行run    改不是模板的文件是有实时刷新的发自我的iPhone------------------ 原始邮件 ------------------发件人: 糖饼  <notifications@github.com>发送时间: 2018年11月23日 18:29收件人: aui/art-template-loader <art-template-loader@noreply.github.com>抄送: keke <web_xiaoke@163.com>, Author <author@noreply.github.com>主题: 回复：[aui/art-template-loader] 每次修改都要执行 npm run ,有没有实时编译的？ (#40)你可以去了解下 webpack 的 watch

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aui/art-template-loader","title":"aui/art-template-loader","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/aui/art-template-loader"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aui in #40: 你可以去了解下 webpack 的 watch"}],"action":{"name":"View Issue","url":"https://github.com/aui/art-template-loader/issues/40#issuecomment-441204854"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/aui/art-template-loader/issues/40#issuecomment-441204854",
"url": "https://github.com/aui/art-template-loader/issues/40#issuecomment-441204854",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [aui/art-template-loader] 每次修改都要执行 npm run ,有没有实时编译的？ (#40)",
"sections": [
{
"text": "",
"activityTitle": "**糖饼**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@aui",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"aui/art-template-loader\",\n\"issueId\": 40,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/aui/art-template-loader/issues/40#issuecomment-441204854"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 415240361\n}"
}
],
"themeColor": "26292E"
}
]
