### ISSUE TITLE
filter只能用标准语法？如何用原始语法？

### ISSUE THREAD

**Issue by kikaendeavor** [aui/art-template-loader#45]
示例是ok的
`{{3.14 | parseInt}}`

但是下边这样写无效
`<%= 3.14 | parseInt %>`

问下filter 如何用原始语法？

**Comment by aui** [comment]
1. 请遵循提问规则
2. 这个问题可以通过阅读文档解决

**Comment by kikaendeavor** [comment]
文档中也是标准语法，没有使用原始语法的示例
[art-template-loader filter](https://github.com/aui/art-template-loader/blob/master/example/filter/index.art)

**Comment by aui** [comment]
更多的语法可以看 art-template 本身的文档，loader 项目的文档只告诉你它自己使用入门。

**Comment by kikaendeavor** [comment]
诚不欺我也，
不采用runtime，只需要引入 `art-template/lib/index`

实现如下：
```
var template = require('art-template/lib/index');

template.defaults.imports.weight = function (data) {
  if (!data || typeof data !== 'string') {
    return '';
  }

  ...

  return result;
};
module.exports = template;
```
`<%= $imports.weight('xxxx')%>`


3Q
