### ISSUE TITLE
模板继承问题

### ISSUE THREAD

**Issue by addcky** [aui/art-template-loader#6]
layout这个demo要怎么跑起来？webpack打包后，生成一个layout.js。但是index.art没有跟layout.js产生关联。我自己添加一个html，引入layout.js，在后台确实跑出了模板继承应该出现的效果。但是这样不对啊。不是应该直接渲染到页面吗？大神，有没有详细一点的文档....sos

**Comment by aui** [comment]
所以你的问题是？

**Comment by aui** [comment]
我猜你自己把前端后端弄混淆了。通常 webpack 编译后的代码是应用在前端的，当然也可以在 node 中使用。你只要记住模板编译后得到的是一个函数，运行这个函数得到的是 html，除了这个之外，所有的概念都是你自己要去梳理

**Comment by addcky** [comment]
我说的在后台确实跑出了模板继承应该出现的效果，是指layout.js里面的console.log语句执行效果。应该有一个html文件让浏览器去解析，解析到相应js时，编译模板得到HTML（一段完整的html代码），然后覆盖掉当前页面，再解析一遍（又不对.....）。有点绕进去了。我想问的是，index.art怎么做到在浏览器解析，解析过程中应用‘’骨架‘

**Comment by aui** [comment]
还是没有明白你到底想问什么

**Comment by addcky** [comment]
layout的这个example应该让浏览器解析哪个文件

**Comment by aui** [comment]
example/webpack.config.js 有三个入口文件，它们编译输出到了了 example/dist/[name].js。所以 example/layout/index.js 会编译为  example/dist/layout.js，它就是你 HTML 应该应该引入的入口文件。

```js
{
// ...
	entry: {
		'include': path.join(__dirname, 'include', 'index.js'),
		'layout': path.join(__dirname, 'layout', 'index.js'),
		'filter': path.join(__dirname, 'filter', 'index.js')
	},
// ...
}
```
example/dist/layout.js 演示了如何载入 art 模板并得到 html，它将 html 输出到了控制台，实际前端应用中你应该将 html 插入到 DOM 中: 

```
const render = require('./index.art');
const data = {
    title: 'My Page'
};
const html = render(data);
console.log(html);

module.exports = render;
```

我建议你先去将 webpack 的概念以及 loader 使用清楚，这个问题其实和 art-template-loader 无关。

**Comment by addcky** [comment]
你说的这个我知道啊。用一个layout.html文件引入example/dist/layout.js后，让浏览器解析。在浏览器console.log是得到了编译后的html代码，但这没用啊，应该解析到页面，让用户看到实际效果吧

**Comment by aui** [comment]
所以你的问题是：如何将 html 字符串插入到 DOM？

**Comment by addcky** [comment]
include.js和filter.js都是忘页面局部写入代码，没什么问题，可以html().但是layout.js编译出的是整个DOM，又要重新覆盖一遍？

**Comment by addcky** [comment]
对对对

**Comment by aui** [comment]
那个 example 只是一个演示而已，实际前端应用只需要一个 HTML 片段就好。 `<html>`、`<body>` 等标签你删掉就好了

**Comment by addcky** [comment]
就是说不能整个dom继承？

**Comment by aui** [comment]
前端不行，后端可以。

**Comment by DerrickTel** [comment]
demo怎么运行？

**Comment by huacixu** [comment]
artTemplate模板继承功能，只能在NODEJS环境下运行吗？我直接用Jquery好像没效果，直接输出block标签了
