### ISSUE TITLE
loader在IE8执行错误

### ISSUE THREAD

**Issue by ediaos** [aui/art-template-loader#7]
art-template: 4.9.1
art-template-loader: 1.4.2

问题描述：
- 使用loader在IE8无法正常渲染，
```
提示：
SCRIPT1010: Expected identifier
manifest.7a7c6d482e97cc8e8d44.js (1,1339)
SCRIPT1010: Expected identifier
vendor.cade4194fcc1301d7444.js (1,20772)
SCRIPT1010: Expected identifier
main.76ddba74839b1b7debed.js (1,5835)
SCRIPT1028: Expected identifier, string or number
socket.io.min.js (1,22042)
```

- 然后尝试在html里增加 三个js库，也没能解决
 - es5-shim.min.js
 - es5-sham.min.js
 - json3.min.js

依旧如上错误，并增加了该错误
```
SCRIPT70: Permission denied
es5-shim.min.js (6,11490)
```

不知道是咱们loader暂时不支持IE8的缘故还是一个bug？ 
因为项目正在考虑使用template，但是又需要支持IE8，虽然不使用loader也能使用，但是项目是通过webpack开发，非常希望能够跑通IE8

非常感谢

**Comment by aui** [comment]
使用 shim  后，art-template 本身是支持 IE8 的，loader 编译后的代码并不依赖 art-template。你需要排查具体编译后的代码，针对性的解决问题。

1. 如果使用了 IE8 不支持的原始 js 模板语句，模板编译后也不会被 IE8 支持
2. 确保你自定义的 `imports` 兼容 IE8（如果有）
3. 如果需要他人协助解决你的问题，你应该附上 demo（你的问题只说明了错误发生了，我们却无法得知具体原因）

**Comment by ediaos** [comment]
非常感谢，是使用了不支持的模板，现在已可以正常使用！
关于第三点以后会注意的，非常感谢。
